name: Deploy Build

on:
  workflow_dispatch:

# permissions:
#   contents: read
#   packages: write

# env:
#   REPO: ${{ vars.REPOSITORY }}
#   ARTIFACT_NAME: ${{ vars.BUILD_ARTIFACT_NAME }}

jobs:
  call_build_workflow:
    uses: ./.github/workflows/buid.yaml@workflows
    with:
      deploy: false
      docker: false
  build:
    runs-on: github-actions-runner-self-hosted-k8s-pw
    steps:
      # - name: Checkout Main
      #   uses: actions/checkout@v4
      # - name: Download Build
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: personal-website-build
      #     github-token: ${{ github.token }}
      #     repository: ${{ env.REPO }}
      - run: ls -la
      - run: echo "tag from build is ${{ env.tag }}
