name: Create Docker Image

on:
  workflow_run:
    workflows:
      - Build Release
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REPO: ${{ vars.REPOSITORY }}
  ARTIFACT_NAME: ${{ vars.BUILD_ARTIFACT_NAME }}

jobs:
  build:
    runs-on: github-actions-runner-self-hosted-k8s-pw
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: personal-website-build
          github-token: ${{ github.token }}
          repository: ${{ env.REPO }}
      - run: ls -la ${{ env.ARTIFACT_NAME }}
