name: Build Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/*'
      - '**.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: github-actions-runner-self-hosted-k8s-pw
    if: ${{ github.base_ref == 'main' }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build Application
        run: npm run build
      
